[Rainmeter]
Update=1000
AccurateText=1
OnRefreshAction=[!Hide][!CommandMeasure MeasureScript "UpdateOffsets()"]

[Variables]
; --- TIME OFFSET SETTINGS ---
@include=Variables.inc

; --- APPEARANCE ---
MyFont=Arial Rounded MT Bold
TextFontSize=18
GridSize=40
PadSide=25
PadTopBottom=20
ColCityX=#PadSide#
ColTimeX=185
ColDayX=285
ColDateX=350

; --- COLORS ---
BgColor=0,0,0,64

[StyleText]
FontFace=#MyFont#
FontSize=#TextFontSize#
FontColor=255,255,255,255
StringStyle=Bold
StringEffect=Border
FontEffectColor=0,0,0,255
AntiAlias=1

[M_Local]
Measure=Time

; --- LOGIC ---

[T_Cal]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffCal# * 3600))
Format=%H:%M
DynamicVariables=1
[D_Cal]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffCal# * 3600))
Format=%a
Substitute="Mon":"Mo","Tue":"Tu","Wed":"We","Thu":"Th","Fri":"Fr","Sat":"Sa","Sun":"Su","Пн":"Пн","Вт":"Вт","Ср":"Ср","Чт":"Чт","Пт":"Пт","Сб":"Сб","Вс":"Вс"
DynamicVariables=1
[Date_Cal_M]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffCal# * 3600))
Format=%d.%m.%Y
DynamicVariables=1

[T_Tor]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffTor# * 3600))
Format=%H:%M
DynamicVariables=1
[D_Tor]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffTor# * 3600))
Format=%a
Substitute="Mon":"Mo","Tue":"Tu","Wed":"We","Thu":"Th","Fri":"Fr","Sat":"Sa","Sun":"Su","Пн":"Пн","Вт":"Вт","Ср":"Ср","Чт":"Чт","Пт":"Пт","Сб":"Сб","Вс":"Вс"
DynamicVariables=1
[Date_Tor_M]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffTor# * 3600))
Format=%d.%m.%Y
DynamicVariables=1

[T_UTC]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffUTC# * 3600))
Format=%H:%M
DynamicVariables=1
[D_UTC]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffUTC# * 3600))
Format=%a
Substitute="Mon":"Mo","Tue":"Tu","Wed":"We","Thu":"Th","Fri":"Fr","Sat":"Sa","Sun":"Su","Пн":"Пн","Вт":"Вт","Ср":"Ср","Чт":"Чт","Пт":"Пт","Сб":"Сб","Вс":"Вс"
DynamicVariables=1
[Date_UTC_M]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffUTC# * 3600))
Format=%d.%m.%Y
DynamicVariables=1

[T_Ber]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffBer# * 3600))
Format=%H:%M
DynamicVariables=1
[D_Ber]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffBer# * 3600))
Format=%a
Substitute="Mon":"Mo","Tue":"Tu","Wed":"We","Thu":"Th","Fri":"Fr","Sat":"Sa","Sun":"Su","Пн":"Пн","Вт":"Вт","Ср":"Ср","Чт":"Чт","Пт":"Пт","Сб":"Сб","Вс":"Вс"
DynamicVariables=1
[Date_Ber_M]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffBer# * 3600))
Format=%d.%m.%Y
DynamicVariables=1

[T_Kyi]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffKyi# * 3600))
Format=%H:%M
DynamicVariables=1
[D_Kyi]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffKyi# * 3600))
Format=%a
Substitute="Mon":"Mo","Tue":"Tu","Wed":"We","Thu":"Th","Fri":"Fr","Sat":"Sa","Sun":"Su","Пн":"Пн","Вт":"Вт","Ср":"Ср","Чт":"Чт","Пт":"Пт","Сб":"Сб","Вс":"Вс"
DynamicVariables=1
[Date_Kyi_M]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffKyi# * 3600))
Format=%d.%m.%Y
DynamicVariables=1

[T_Mos]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffMos# * 3600))
Format=%H:%M
DynamicVariables=1
[D_Mos]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffMos# * 3600))
Format=%a
Substitute="Mon":"Mo","Tue":"Tu","Wed":"We","Thu":"Th","Fri":"Fr","Sat":"Sa","Sun":"Su","Пн":"Пн","Вт":"Вт","Ср":"Ср","Чт":"Чт","Пт":"Пт","Сб":"Сб","Вс":"Вс"
DynamicVariables=1
[Date_Mos_M]
Measure=Time
TimeStamp=([M_Local:TimeStamp] + (#OffMos# * 3600))
Format=%d.%m.%Y
DynamicVariables=1

; --- UI METERS ---

[M_Count]
Measure=Calc
Formula=6

[Backing]
Meter=Shape
Shape=Rectangle 0,0,530,(#PadTopBottom# * 2 + ([M_Count]-1) * #GridSize# + 26) | Fill Color #BgColor# | Stroke Color 0,0,0,0
DynamicVariables=1

[L_Cal]
Meter=String
MeterStyle=StyleText
Text="Calgary"
X=#ColCityX#
Y=#PadTopBottom#
[V_Cal]
Meter=String
MeterStyle=StyleText
MeasureName=T_Cal
X=#ColTimeX#
Y=0r
[Day_Cal]
Meter=String
MeterStyle=StyleText
MeasureName=D_Cal
X=#ColDayX#
Y=0r
[Date_Cal]
Meter=String
MeterStyle=StyleText
MeasureName=Date_Cal_M
X=#ColDateX#
Y=0r

[L_Tor]
Meter=String
MeterStyle=StyleText
Text="Toronto"
X=#ColCityX#
Y=#GridSize#r
[V_Tor]
Meter=String
MeterStyle=StyleText
MeasureName=T_Tor
X=#ColTimeX#
Y=0r
[Day_Tor]
Meter=String
MeterStyle=StyleText
MeasureName=D_Tor
X=#ColDayX#
Y=0r
[Date_Tor]
Meter=String
MeterStyle=StyleText
MeasureName=Date_Tor_M
X=#ColDateX#
Y=0r

[L_UTC]
Meter=String
MeterStyle=StyleText
Text="UTC"
X=#ColCityX#
Y=#GridSize#r
[V_UTC]
Meter=String
MeterStyle=StyleText
MeasureName=T_UTC
X=#ColTimeX#
Y=0r
[Day_UTC]
Meter=String
MeterStyle=StyleText
MeasureName=D_UTC
X=#ColDayX#
Y=0r
[Date_UTC]
Meter=String
MeterStyle=StyleText
MeasureName=Date_UTC_M
X=#ColDateX#
Y=0r

[L_Ber]
Meter=String
MeterStyle=StyleText
Text="Berlin"
X=#ColCityX#
Y=#GridSize#r
[V_Ber]
Meter=String
MeterStyle=StyleText
MeasureName=T_Ber
X=#ColTimeX#
Y=0r
[Day_Ber]
Meter=String
MeterStyle=StyleText
MeasureName=D_Ber
X=#ColDayX#
Y=0r
[Date_Ber]
Meter=String
MeterStyle=StyleText
MeasureName=Date_Ber_M
X=#ColDateX#
Y=0r

[L_Kyi]
Meter=String
MeterStyle=StyleText
Text="Kyiv"
X=#ColCityX#
Y=#GridSize#r
[V_Kyi]
Meter=String
MeterStyle=StyleText
MeasureName=T_Kyi
X=#ColTimeX#
Y=0r
[Day_Kyi]
Meter=String
MeterStyle=StyleText
MeasureName=D_Kyi
X=#ColDayX#
Y=0r
[Date_Kyi]
Meter=String
MeterStyle=StyleText
MeasureName=Date_Kyi_M
X=#ColDateX#
Y=0r

[L_Mos]
Meter=String
MeterStyle=StyleText
Text="Moscow"
X=#ColCityX#
Y=#GridSize#r
[V_Mos]
Meter=String
MeterStyle=StyleText
MeasureName=T_Mos
X=#ColTimeX#
Y=0r
[Day_Mos]
Meter=String
MeterStyle=StyleText
MeasureName=D_Mos
X=#ColDayX#
Y=0r
[Date_Mos]
Meter=String
MeterStyle=StyleText
MeasureName=Date_Mos_M
X=#ColDateX#
Y=0r


[MeasureScript]
Measure=Script
ScriptFile=TimeScript.lua
UpdateDivider=-1